---
# This file is a template, and might need editing before it works on your project.


stages:
  - test


# This is a basic example for a packages or script which doesn't use
# services such as redis or postgres
before_script:
  # Setup git
  - apt-get install git
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  # Install dependencies for the testing environment
  - pip install -U pip setuptools
  - pip install -U tox

.test_script:
  script:
    # runs the python tests
    - tox
  artifacts:
    when: always
    reports:
      junit: report.xml

  tags:
    - docker
    - test
    - tox
  variables:
    GIT_SUBMODULE_STRATEGY: normal


pytest:
  stage: test
  image: "python:3.8"
  extends: .test_script
